"""init

Revision ID: 5d632c7a82e4
Revises: 
Create Date: 2026-02-02 00:25:53.720350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5d632c7a82e4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('storage_url', sa.Text(), nullable=False),
    sa.Column('mime', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('source', 'mix')", name='ck_audio_assets_kind'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mixes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('current_ready_revision_no', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mix_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mix_id', sa.UUID(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('analysis_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_audio_asset_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['mix_id'], ['mixes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_audio_asset_id'], ['audio_assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_mix_items_mix_id_added_at', 'mix_items', ['mix_id', 'added_at'], unique=False)
    op.create_table('mix_revisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mix_id', sa.UUID(), nullable=False),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('switchover_ms', sa.Integer(), nullable=False),
    sa.Column('length_ms', sa.Integer(), nullable=False),
    sa.Column('audio_asset_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length_ms > 0', name='ck_mix_revisions_length_ms_pos'),
    sa.CheckConstraint('switchover_ms >= 0', name='ck_mix_revisions_switchover_ms_nonneg'),
    sa.ForeignKeyConstraint(['audio_asset_id'], ['audio_assets.id'], ),
    sa.ForeignKeyConstraint(['mix_id'], ['mixes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mix_id', 'revision_no', name='uq_mix_revisions_mix_id_revision_no')
    )
    op.create_index('ix_mix_revisions_mix_id_revision_no', 'mix_revisions', ['mix_id', 'revision_no'], unique=False)
    op.create_table('rooms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('mix_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('play_started_at_epoch_ms', sa.BigInteger(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['mix_id'], ['mixes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rooms_created_at', 'rooms', ['created_at'], unique=False)
    op.create_index('ix_rooms_deleted_at', 'rooms', ['deleted_at'], unique=False)
    op.create_table('mix_segments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mix_revision_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('mix_item_id', sa.UUID(), nullable=False),
    sa.Column('start_ms', sa.Integer(), nullable=False),
    sa.Column('end_ms', sa.Integer(), nullable=False),
    sa.Column('source_start_ms', sa.Integer(), nullable=False),
    sa.CheckConstraint('end_ms > start_ms', name='ck_mix_segments_end_gt_start'),
    sa.CheckConstraint('source_start_ms >= 0', name='ck_mix_segments_source_start_nonneg'),
    sa.CheckConstraint('start_ms >= 0', name='ck_mix_segments_start_nonneg'),
    sa.ForeignKeyConstraint(['mix_item_id'], ['mix_items.id'], ),
    sa.ForeignKeyConstraint(['mix_revision_id'], ['mix_revisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mix_revision_id', 'position', name='uq_mix_segments_revision_pos')
    )
    op.create_index('ix_mix_segments_revision_pos', 'mix_segments', ['mix_revision_id', 'position'], unique=False)
    op.create_table('room_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('seq', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sender_name', sa.Text(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id', 'seq', name='uq_room_messages_room_seq')
    )
    op.create_index('ix_room_messages_room_seq', 'room_messages', ['room_id', 'seq'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_room_messages_room_seq', table_name='room_messages')
    op.drop_table('room_messages')
    op.drop_index('ix_mix_segments_revision_pos', table_name='mix_segments')
    op.drop_table('mix_segments')
    op.drop_index('ix_rooms_deleted_at', table_name='rooms')
    op.drop_index('ix_rooms_created_at', table_name='rooms')
    op.drop_table('rooms')
    op.drop_index('ix_mix_revisions_mix_id_revision_no', table_name='mix_revisions')
    op.drop_table('mix_revisions')
    op.drop_index('ix_mix_items_mix_id_added_at', table_name='mix_items')
    op.drop_table('mix_items')
    op.drop_table('mixes')
    op.drop_table('audio_assets')
    # ### end Alembic commands ###
